spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amazen?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

jwt:
  token:
    secret: fdjk34xm3=
    lifetime: 30000000

server:
  port: 5100

  error:
    include-message: always

  servlet:
    context-path: /api